jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: deep-equator-469204-b7
          export_default_credentials: true

      - name: Build and push Docker image
        run: |
          gcloud builds submit --tag gcr.io/deep-equator-469204-b7/my-app-backend

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-backend \
            --image gcr.io/deep-equator-469204-b7/my-app-backend \
            --region asia-south1 \
            --platform managed \
            --allow-unauthenticated
