name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id:deep-equator-469204-b7
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Build and push Docker image to Google Container Registry
        run: |
          gcloud builds submit --tag gcr.io/YOUR_GCP_PROJECT_ID/YOUR_IMAGE_NAME

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-backend \
            --image gcr.io/deep-equator-469204-b7/my-app-backend \
            --region asia-south1 \
            --platform managed \
            --allow-unauthenticated
